
export const suggestions = [
    { label: 'Afghanistan', id: 'Afg'  },
    { label: 'Aland Islands', id: 'Ala'  },
    { label: 'Albania', id: 'Alb'  },
    { label: 'Algeria', id: 'Alg'  },
    { label: 'American Samoa', id: 'Ame'  },
    { label: 'Andorra', id: 'And'  },
    { label: 'Angola', id: 'Ang'  },
    { label: 'Anguilla', id: 'Anu'  },
    { label: 'Antarctica', id: 'Ant'  },
    { label: 'Antigua and Barbuda', id: 'Ani'  },
    { label: 'Argentina', id: 'Arg'  },
    { label: 'Armenia', id: 'Arm'  },
    { label: 'Aruba', id: 'Aru'  },
    { label: 'Australia', id: 'Aus'  },
    { label: 'Austria', id: 'Aut'  },
    { label: 'Azerbaijan', id: 'Aze'  },
    { label: 'Bahamas', id: 'Bah'  },
    { label: 'Bahrain', id: 'Bar'  },
    { label: 'Bangladesh', id: 'Ban'  },
    { label: 'Barbados', id: 'Bar'  },
    { label: 'Belarus', id: 'Bel'  },
    { label: 'Belgium', id: 'Beg'  },
    { label: 'Belize', id: 'Bei'  },
    { label: 'Benin', id: 'Ben'  },
    { label: 'Bermuda', id: 'Ber'  },
    { label: 'Bhutan', id: 'Bhu'  },
    { label: 'Bolivia, Plurinational State of', id: 'Bol'  },
    { label: 'Bonaire, Sint Eustatius and Saba', id: 'Bon'  },
    { label: 'Bosnia and Herzegovina', id: 'Bos'  },
    { label: 'Botswana', id: 'Bot'  },
    { label: 'Bouvet Island', id: 'Bou'  },
    { label: 'Brazil', id: 'Bra'  },
    { label: 'British Indian Ocean Territory', id: 'Bri'  },
    { label: 'Brunei Darussalam', id: 'Bru'  },
  ];